name: donuts_app_8sc
description: "A new Flutter project."
publish_to: "none" # Para que no se publique en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons para estilo iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets del proyecto
  assets:
    - lib/images/
    - lib/icons/
